use_frameworks!

platform :ios, '10.0'

target 'TMNavigationController_Example' do
  pod 'TMNavigationController', :path => '../'

  target 'TMNavigationController_Tests' do
    inherit! :search_paths

    
  end
end
